<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN">
<head>
	<meta charset="UTF-8" />
	<?php echo $this->headTitle() ?>
	<?php echo $this->headMeta() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>
	<?php echo $this->headScript() ?>
</head>
<body>
<?php echo $this->placeholder('message');// 输出提示信息 ?>
<?php echo $this->layout()->content; ?>	
</body>
</html>
